### ISSUE TITLE
Quran360.sdf is missing

### ISSUE THREAD

**Issue by faisalr** [FlairWork/Quran360WindowsPhone#1]
Quran360.sdf is missing

**Comment by hanifw** [comment]
A bit new to github, not so sure how to upload the file into this folder.

**Comment by faisalr** [comment]
look at gitignore

remove .sdf from it

and upload again

Date: Mon, 29 Jul 2013 14:37:22 -0700

**Comment by hanifw** [comment]
Uploaded, thanks!
